BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Vehiculo] ALTER COLUMN [padron] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[Vehiculo] ALTER COLUMN [codigoNacional] INT NULL;
ALTER TABLE [dbo].[Vehiculo] ALTER COLUMN [divNum] INT NULL;
ALTER TABLE [dbo].[Vehiculo] ALTER COLUMN [combustible] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
